function [io timings shapes] = example_structs()
% io defines input and output parameters, channels used etc.
    % Fs - sampling freq DSP
    % inputchans - channels selected on CS
    % outputchans - output channels used on CS, necessary for calibration
io = struct('Fs', 6000, 'inputchans', 1:4, 'outputchans', 9:12);

% timings defines timings of pulses
timings = struct('trainfreq', {[4 4] , 4, 4, 4}, ...
                 'traindur', {[1 5], 5, 4, 2}, ...
                 'offsets', {[1000 100], 0, 50, 2000});

shapes = struct('modes', {{'rect', 'sine'}, 'rampUp', 'triang', 'rampDown'}, ...
                'Vvals', {[3 1], 2, 3, 4}, ...
                'pulsefreq', {[NaN 25], 2, 3, 4}, ...
                'pulsedur', {[100 200], 100, 100, 100}, ...
                'desc', []); 
end
