function desc = chan_zero()

timings = struct(   'trainfreq', {0}, ...
                    'traindur', {0}, ...
                    'offsets', {0}, ...
                    'template', {[]});
                    
shapes = struct(    'modes', {'rect'}, ...
                    'Vvals', {0}, ...
                    'pulsefreq', {[]}, ...
                    'pulsedur', {0}, ...
                    'template', {[]});

desc = struct('io', io_m428, 'timings', timings, 'shapes', shapes);