function desc = full_calibration()
io = struct(  'Fs', 6000, ...
                'inputchans', 1, ...
                'outputchans', 9, ...
                'animal', 'none', ...
                'padding', [], ...
                'template', []);

timings = struct(   'trainfreq', 0.5, ...
                    'traindur', 6, ...
                    'offsets', 0, ...
                    'template', []);
                    
shapes = struct(    'modes', 'rect', ...
                    'Vvals', 1, ...
                    'pulsefreq', [], ...
                    'pulsedur', 800, ...
                    'template', []);

desc = struct('io', io, 'timings', timings, 'shapes', shapes);