function desc = full_simple()

timings = struct(   'trainfreq', 1, ...
                    'traindur', 10, ...
                    'offsets', 0, ...
                    'template', []);
                    
shapes = struct(    'modes', 'rect', ...
                    'Vvals', 1, ...
                    'pulsefreq', [], ...
                    'pulsedur', 50, ...
                    'template', []);

desc = struct('io', io_ch9to12, 'timings', repmat(timings, 1, 4), 'shapes', repmat(shapes, 1, 4));