function desc = io_ch9to12()

desc = struct(  'Fs', 6000, ...
                'inputchans', 1:4, ...
                'outputchans', 9:12, ...
                'animal', 'unspecified', ...
                'padding', [], ...
                'template', []);

