function desc = io_ch9()

desc = struct(  'Fs', 6000, ...
                'inputchans', 1, ...
                'outputchans', 9, ...
                'animal', 'none', ...
                'padding', [], ...
                'template', []);

