function desc = io_m428()

desc = struct(   'Fs', 6000, ...
                'inputchans', 1:4, ...
                'outputchans', 9:12, ...
                'animal', 'm428', ...
                'template', []);

